### ISSUE TITLE
AttributeError: 'PerspectiveManager' object has no attribute 'host_view' 

### ISSUE THREAD

**Issue by arniwesth** [sc1f/streaming-perspective-jupytercon-2020#2]
Great talk! 

I got this when trying to run the tornado server
```
$ python3 tornado_server.py
Traceback (most recent call last):
  File "tornado_server.py", line 118, in <module>
    app = make_app()
  File "tornado_server.py", line 93, in make_app
    MANAGER.host_view("holdings_view", VIEWS["holdings"])
AttributeError: 'PerspectiveManager' object has no attribute 'host_view'
```

**Comment by sc1f** [comment]
The example here has bit-rotted vs. the latest version of Perspective (0.10.0). I just pushed up an update to tornado_server that should work with the latest version of Perspective.

**Comment by arniwesth** [comment]
Thanks! Ones small correction to get the server example to work:
```iex_source=client.last``` should be replaced with ```iex_source=client.iexLast```
